
services:
  db-app:
    image: postgres:17.4-alpine3.21
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db-app
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  # worker:
  #   build: .
  #   volumes:
  #     - .:/app
  #   command: python src/manage.py qcluster
  #   depends_on:
  #     - db-app
  #     - redis

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data/

volumes:
  db_data:
  redis_data:
