
services:
  db-app:
    image: postgres:17.4-alpine3.21
    ports:
      - 15432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # worker:
  #   build: .
  #   volumes:
  #     - .:/app
  #   command: python src/manage.py qcluster
  #   depends_on:
  #     - db-app
  #     - redis

  redis:
    image: redis:7.4.2-alpine
    ports:
      - 16379:6379
    volumes:
      - redis_data:/data/

volumes:
  db_data:
  redis_data:
